[33기 김혜수] ADD: 장바구니 기능 추가
wecode-bootcamp-korea/33-2nd-yakurt-frontend pull request #10
Opened 2022-06-12 06:06 UTC by keemhyesu

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-06-13 02:30 UTC, younuk23 requested changes
- 리뷰 확인 및 반영해주세요!
- 브랜치 잘 나누시는것 너무 좋네요!
- map 메서드에 대한 이해가 이제서야 감이 잡히는 것 같다.. 역시 코드는 많이 쳐봐야 한다고 느낌! => 👍 
- 하지만...! 커밋 메세지는 제대로 작성해주세요! 기본적이면서도 잘 안지키게 되는 건데, 실제 기업레벨에서 커밋메세지 이렇게 작성되어 있으면 코드안보고 바로 패스합니다!
***
- 명확한 작업내용이 드러나도록 커밋 메세지 기록해주세요
- 커밋 메세지가 불분명하면 추후 이 커밋에서 어떤 작업을 했는지 알아보기 힘듭니다.
- 커밋 메세지는 되도록 한줄이 아니라 제목과 본문을 나눠서 작성하면서 상세한 작업내용을 기록해주세요
- 커밋 메세지의 작성 포맷에 대해서는 아래 문서를 참고해보세요
- [커밋 메세지 가이드라인](https://study.wecode.co.kr/session/content/123)

2022-06-13 02:30 UTC, younuk23 commented on src/pages/Cart/Cart.js
> +          <p>{totalPrice.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',')}원</p>
toLocaleString method로 동일한 기능을 구현할 수 있습니다!

2022-06-14 05:37 UTC, younuk23 requested changes
커밋메세지 잘 수정해주셨네요! 👍 
리뷰 확인 및 반영해주세요!

2022-06-14 05:37 UTC, younuk23 commented on src/pages/Cart/Cart.js
>  const ProductLists1 = styled(Content)``;
```suggestion
const ProductLists1 = styled(Content)``;
```

추가적인 스타일을 보여줄 필요가 없다면 굳이 상속받아서 새로운 스타일드 컴포넌트를 만들 필요 없이 Content 컴포넌트를 그대로 사용해도 될 것 같네요!

2022-06-14 05:37 UTC, younuk23 commented on src/pages/Cart/Cart.js
> +  console.log(itemListValue);
사이더 코멘트 해결해주세요!

2022-06-14 05:37 UTC, younuk23 commented on src/components/Cart/ProductList.js
> +  }, [boxChecking]); //의존성배열????ㅇㅋㅇㅋ boxChecking이 바뀔때마다 함수 실행
주석... 고뇌의 흔적이 master에 남도록 하진 말아주세요!

2022-06-14 05:37 UTC, younuk23 commented on src/pages/Cart/TempCart.js
>  const TempCart = () => {
이전에 드렸던 코멘트처럼 TempCart라는 이름보다는 "카트가 비어있을 때 보여주는 컴포넌트다" 라는게 드러나는 이름으로 지어주면 좀 더 잘 알아볼 수 있을 것 같네요!

2022-06-14 06:10 UTC, keemhyesu commented on src/components/Cart/ProductList.js
> +  }, [boxChecking]); //의존성배열????ㅇㅋㅇㅋ boxChecking이 바뀔때마다 함수 실행
하핫 주의하겠습니다..

2022-06-14 07:00 UTC, younuk23 approved these changes
LGTM 👍

2022-06-14 07:00 UTC, merged