[33기 천은별] Modify: 리뷰 페이지 Conflict 해결
wecode-bootcamp-korea/33-2nd-yakurt-frontend pull request #4
Opened 2022-06-08 13:12 UTC by eunbyulcheon

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 고객 리뷰 페이지 레이아웃. 
- 고객 리뷰 form 레이아웃. 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-06-09 01:16 UTC, younuk23 requested changes
리뷰 확인 및 반영해주세요! 다른 브랜치에서도 해당하는 내용 수정해주세요!

2022-06-09 01:16 UTC, younuk23 commented on src/components/review/Content.js
> +export default Content;
review 페이지 안에서만 쓰이는 컴포넌트라면, components/review가 아니라, pages/review 디렉토리 안에서 위치하는게 좋아보이네요! 다른 PR도 마찬가지입니다.

- components/ -> 여러 페이지에서 공통적으로 사용하는 컴포넌트
페이지 안에서만 사용되는 컴포넌트라면 해당 페이지 디렉토리 안에 위치시켜주세요!

2022-06-10 02:25 UTC, younuk23 approved these changes
LGTM 👍

2022-06-10 02:25 UTC, younuk23 commented
컨플릭 해결해주세요!

2022-06-10 07:51 UTC, younuk23 commented
은별님 머지말고 rebase로 브랜치 병합 진행해주세요!!

2022-06-10 09:44 UTC, younuk23 commented
- 컨플릭 해결해주세요! 찐막

2022-06-10 10:06 UTC, eunbyulcheon commented
> 

ㅋㅋㅋㅋㅋ 리베이스 했습니다 ^^

2022-06-10 10:27 UTC, merged