[33기 김혜수] ADD: 장바구니 Layout 구현
wecode-bootcamp-korea/33-2nd-yakurt-frontend pull request #5
Opened 2022-06-08 15:15 UTC by keemhyesu

-장바구니 Layout 완성
-style component 사용

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 장바구니 페이지 Layout 완성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-06-08 15:16 UTC, ghost commented on src/pages/Cart.js
> +import React, { useCallback, useState } from 'react';
__[ESLint]__ 'useState' is defined but never used. ([view](https://sider.review/gh/repos/500715035/pulls/5#issue-6975109))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `no-unused-vars` | `warn` | Yes |

References:
- <https://eslint.org/docs/rules/no-unused-vars>

You can [close this issue](https://sider.review/gh/repos/500715035/pulls/5#issue-6975109) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-06-08 15:16 UTC, ghost commented on src/pages/Cart.js
> +const CART_ITEM = [
__[ESLint]__ 'CART_ITEM' is assigned a value but never used. ([view](https://sider.review/gh/repos/500715035/pulls/5#issue-6975110))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `no-unused-vars` | `warn` | Yes |

References:
- <https://eslint.org/docs/rules/no-unused-vars>

You can [close this issue](https://sider.review/gh/repos/500715035/pulls/5#issue-6975110) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-06-09 01:18 UTC, younuk23 commented
- PR 본문 예시 문장 삭제해주세요!
- PR 본문 최근 작업 주제 위에 양식에 맞지 않게 내용이 들어가 있네요 꼼꼼히 확인해주세요!
- 사이더 코멘트 해결해주세요!

2022-06-09 05:42 UTC, younuk23 commented
혜수님
- rebase 진행해서 커밋 하나로 합쳐주세요!
- PR 본문 여전히 깨져있습니다 반드시 꼼꼼히 확인해주세요!!

2022-06-10 02:30 UTC, younuk23 requested changes
리뷰 확인 및 반영해주세요~!

2022-06-10 02:30 UTC, younuk23 commented on src/components/ProductList.js
> +const Products = styled.div`
위에 공백 한줄 들어가는게 좋겠네요!

2022-06-10 02:30 UTC, younuk23 commented on src/components/Payment.js
> +export default Payment;
export랑 스타일드 컴포넌트 선언문 사이에 공백한줄 들어가는게 좋겠네요!

2022-06-10 02:30 UTC, younuk23 commented on src/pages/Cart.js
> +  useEffect(() => {
effect랑 state 선언문 사이에 공백 부여해주세요!

2022-06-10 02:30 UTC, younuk23 commented on src/pages/Cart.js
> +      // },
나중에 실제 Authoriation이 필요할 때 추가하면 되는 코드 같네요 지금 굳이 주석처리해둘 필요 없어보입니다!

2022-06-10 02:30 UTC, younuk23 commented on src/pages/Cart.js
> +    //result.result <- 객체 안의 배열로 들어가는 어쩌구
불필요한 주석으로 보이네요!

2022-06-10 02:30 UTC, younuk23 commented on src/pages/Cart.js
> +`;
이런 방식이라면 h3를 스타일드 컴포넌트로 만드는게 더 좋아보입니다!

2022-06-10 02:30 UTC, younuk23 commented on src/pages/Cart.js
> +`;
그리고 대부분 속성이 같다면 스타일드 컴포넌트를 상속해서 활용하는 방안도 적용해보세요!

2022-06-10 02:30 UTC, younuk23 commented on src/pages/Cart.js
> +  const [listValue, setListValue] = useState([]);
listValue라는 변수명은 보고 어떤 정보인지 전혀 알수가 없어보입니다! 항상 이름을 지을 땐 의미가 명확하게 드러나도록 고민해주세요!
지금부터 잘 고민하는 습관을 들이셔야 합니다!

2022-06-10 02:30 UTC, younuk23 commented on src/pages/TempCart.js
> +function TempCart() {
TempCart는 무슨 용도인가요?

2022-06-10 05:22 UTC, keemhyesu commented on src/pages/TempCart.js
> +function TempCart() {
장바구니가 비어있을때의 페이지 레이아웃입니다!

2022-06-10 08:49 UTC, younuk23 commented on src/pages/TempCart.js
> +function TempCart() {
혜수님 해결되지 않은 대화는 resolve 누르지 말아주세요! 완전히 반영이 다 됬다고 생각되는 것들만 누르시면 됩니다!(이건 리뷰 해주시는분마다 방식이 다를 순 있어요)

2022-06-10 08:49 UTC, younuk23 commented on src/pages/TempCart.js
> +function TempCart() {
비어있을때라면 비어있을때라는 이름으로 지어주는게 좋을 것 같네요 Empty등?, Temp는 임시적인 의미로보이는데, 그래서 비어있을때 레이아웃이랑은 다른 것 같네요 의미가!

2022-06-10 09:33 UTC, younuk23 approved these changes
LGTM 👍

2022-06-10 09:33 UTC, merged

2022-06-10 09:34 UTC, younuk23 commented
파일명 변경은 다음 브랜치에서 적용 해주세요!