[33기 김완영]ADD:Order Page 구현
wecode-bootcamp-korea/33-2nd-yakurt-frontend pull request #7
Opened 2022-06-10 02:58 UTC by kimwanyoung

- 주문페이지 레이아웃 구현
- 커스텀 훅 적용하여 fetch 및 주소검색 api 구현
- 체크박스 전체 선택 구현

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 주문 페이지 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 카카오 주소 api 받아와서 주소 검색 기능 추가하였습니다.
2. 커스텀 훅 적용하여 관심사 분리
3. 체크박스 전체 선택기능 state이용하여 전체 선택시 배열에 담고 해제하면 배열을 전부 비우고 밑에 있는 체크박스 클릭 시 state추가하고 그렇지않으면 filter함수 이용하여 필터링하여 구현하였습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항
- 커스텀훅을 이렇게 사용하는게 맞는지 확실하게 잘 모르겠습니다.

2022-06-10 09:41 UTC, younuk23 requested changes
금지령 몇개 남겨드렸습니다..

2022-06-10 09:41 UTC, younuk23 commented on src/pages/order/CheckBox.js
> +      setCheckedLists(checkedListArr);
```suggestion
      setCheckedLists([...DATALIST]);
```

2022-06-10 09:41 UTC, younuk23 commented on src/pages/order/CheckBox.js
> +];
변수명 el 금지, DATALIST 등 의미를 파악할 수 없는 것 금지... ❌

2022-06-10 09:41 UTC, younuk23 commented on src/pages/order/OrderItem.js
> +        <img src={imgUrl} alt="img" />
img?

2022-06-10 09:41 UTC, younuk23 commented on src/pages/order/OrderItem.js
> +        <img src={imgUrl} alt="img" />
alt 그냥 채우기 금지 ❌

2022-06-10 09:42 UTC, kimwanyoung commented on src/pages/order/OrderItem.js
> +        <img src={imgUrl} alt="img" />
ㅎㅎ.. 명심하겠습니다

2022-06-13 01:49 UTC, younuk23 requested changes
리뷰 확인 및 반영해주세요!

2022-06-13 01:49 UTC, younuk23 commented on src/hooks/Fetch.js
> +};
이건 단순히 Get에만 사용할 수 있는 형태로 보이네요! 좀 더 다양하게 사용할 수 있도록 확장하는 것 다음 브랜치에서 시도해보세요!

2022-06-13 01:49 UTC, younuk23 commented on src/pages/order/CheckBox.js
> +      CHECKBOX_AGREEMENT.forEach(Agreementlist =>
why Pascal?....

2022-06-13 01:49 UTC, younuk23 commented on src/pages/order/CheckBox.js
> +      CHECKBOX_AGREEMENT.forEach(Agreementlist =>
잘 신경써주세요! 제일 기본적인 부분입니다! 기본적인 코딩 스타일이 잘 지켜지지 않은 코드는 아무리 구현이 좋더라도 안좋은 평가를 받을수 있습니다!

2022-06-13 01:49 UTC, younuk23 commented on src/pages/order/CheckBox.js
> +    }
```suggestion
   const newCheckedList = checked ? [...CHECKBOX_AGREEMENT] : [];
   setCheckedList(newCheckedList);
```

불필요하게 명령형으로 써져있는 것 같네요 선언적으로 간단하게 표현할 수 있어보입니다!

2022-06-13 01:49 UTC, younuk23 commented on src/pages/order/CheckBox.js
> +          }
```suggestion
          checked={checkedList.length === CHECKBOX_AGREEMENT.length}
```

결국 이 조건과 동일한 것 같은데 기존 코드처럼 처리하신 이유가 있으신가요?

2022-06-13 01:49 UTC, younuk23 commented on src/pages/order/OrderItem.js
> +      <span>{price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',')}원</span>
toLocaleString method를 사용하는 방법도 있습니다!

2022-06-13 01:49 UTC, younuk23 commented on src/pages/order/PostApi.js
> +    }
코드상으로만 보면 동작을 이해하기가 너무 힘든데, 좀 더 직관적으로 표현할 수 있는 방법은 없을까요?

2022-06-14 06:58 UTC, younuk23 approved these changes
LGTM 👍

2022-06-14 06:58 UTC, merged